apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wjsp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0064-tenant/tkrw-pr712-0075-0064-app/devfile-sample-wjsp@sha256:b758f6a0744076cf135ba4647f04d92cd0a0a4c8f1755e8a1081410af0536b90
        name: my-nodejs
        resources: {}
status: {}
